"""Explicacoes das questoes do exercicio debugger (parte 1).

O texto esta em ROT13 de proposito - ele diz qual eh a resposta certa,
e em claro bastaria rolar o arquivo pra ver tudo.

Voce nao precisa abrir este arquivo. Use a funcao explicar() do
exercicio, que decodifica e imprime:

    explicar('total_apos_2a_iteracao')

GERADO AUTOMATICAMENTE por NAO_MANDAR_montar_explicacao_debugger.py -
nao edite aqui, edite la e rode de novo.
"""

EXPLICACOES = {
    'qual_opcao_do_play': '\nFnb dhngeb bcpbrf ab zrah, r rynf fr qvivqrz rz qhnf qhcynf.\n\nNf qhnf qr pvzn ("Eha Clguba Svyr" r "Eha Clguba Svyr va Qrqvpngrq\nGrezvany") EBQNZ b nedhvib qb pbzrpb nb svz. Rynf anb fnorz dhr\noernxcbvag rkvfgr: n obyvaun irezryun svpn yn, b cebtenzn cnffn cbe pvzn\nr grezvan. N qvsrerapn rager nf qhnf ru fb rz dhny grezvany n fnvqn\nncnerpr - arauhzn qnf qhnf freir cen rfgn yvfgn.\n\nNf qhnf qr onvkb pbzrpnz pbz "Clguba Qrohttre" r cnenz abf oernxcbvagf. N\ndhr ibpr dhre ru n dhr ebqn RFGR nedhvib qvergb: "Clguba Qrohttre: Qroht\nClguba Svyr".\n\nN hygvzn ("Qroht hfvat ynhapu.wfba") gnzorz ru qrohttre, znf ryn cebphen\nhz nedhvib qr pbasvthenpnb punznqb ynhapu.wfba cen fnore b dhr ebqne r\npbz dhnvf nethzragbf. Vffb freir cen cebwrgb tenaqr, pbz inevbf cbagbf qr\nragenqn. Ndhv anb un ynhapu.wfba arauhz - fr ibpr rfpbyure rffn, b IFPbqr\ninv gr crqve cen pevne hz, r ibpr anb cerpvfn qvffb.\n\nErten cengvpn: fr n bcpnb anb pbzrpn pbz "Clguba Qrohttre", ryn anb cnen.\n',

    'valor_de_indice_ultima': "\nN crethagn ru b dhr b CNVARY zbfgen, anb b dhr qrivn zbfgene.\n\nN yvaun N ru\n\n    vaqvpr_hygvzn = yra(znb)\n\nr n znb ru ['Np', '5c'], dhr grz qhnf pnegnf. Ragnb yra(znb) inyr 2, r b\ncnvary zbfgen vaqvpr_hygvzn = 2.\n\nFr ibpr erfcbaqrh 1, ibpr erfcbaqrh b dhr n yvaun QRIREVN gre srvgb -\nrffr ru b inybe pregb ceb hygvzb vaqvpr, r ru whfgnzragr cbe vffb dhr b\npbafregb rkvfgr. Znf n crethagn ren b dhr n inevniry INYR ntben, pbz b\noht nvaqn ab yhtne.\n\nRffn qvfgvapnb ru b unovgb dhr n yvfgn vagrven dhre pbafgehve: cevzrveb\nbofreine b dhr npbagrpr, qrcbvf whytne fr rfgn pregb. Fr ibpr wn purtn\nerfcbaqraqb b dhr qrivn npbagrpre, b qrohttre anb gr freir cen anqn.\n\nQrgnyur qr yrvghen qb cnvary: n frgn nzneryn ncbagn n yvaun dhr inv\nebqne NTBEN - bh frwn, dhr nvaqn ANB ebqbh. Fr ibpr byubh b cnvary pbz n\nfrgn nvaqn an yvaun N, b vaqvpr_hygvzn arz rkvfgvn nvaqn. Qn hz fgrc bire\ncevzrveb.\n",

    'maior_indice_valido': "\nN znb ru ['Np', '5c']: qhnf pnegnf.\n\n    znb = ['Np', '5c']\n    #        0     1\n\nBf vaqvprf pbzrpnz ab MREB, ragnb nf cbfvpbrf dhr rkvfgrz fnb 0 r 1. B\nznvbe vaqvpr inyvqb ru 1.\n\nFr ibpr erfcbaqrh 2, ibpr erfcbaqrh b GNZNAUB qn yvfgn, anb n hygvzn\ncbfvpnb. Fnb qhnf pbvfnf qvsreragrf r n qvsrerapn ru frzcer 1 - ru b\nsnzbfb bss-ol-bar. Ahzn yvfgn qr a ryrzragbf, b hygvzb vaqvpr ru a - 1.\n\nPbzcner pbz n erfcbfgn nagrevbe: vaqvpr_hygvzn inyr 2, r b znvbe vaqvpr\ndhr rkvfgr ru 1. Npubh b oht? N yvaun N crqr hzn cbfvpnb dhr n znb anb\ngrz.\n",

    'tipo_do_erro': '\nB reeb ru b VaqrkReebe. N erfcbfgn fr rfperir pbzb grkgb:\n\n    gvcb_qb_reeb = \'VaqrkReebe\'\n\nB Clguba yrinagn ryr dhnaqb ibpr crqr hzn cbfvpnb dhr anb rkvfgr an\nyvfgn. N zrafntrz pbzcyrgn dhr ncnerpr ru\n\n    VaqrkReebe: yvfg vaqrk bhg bs enatr\n\nr "yvfg vaqrk bhg bs enatr" ru yvgrenyzragr "vaqvpr qr yvfgn sben qb\nnypnapr". N crethagn crqvn fb b ABZR, nagrf qbf qbvf cbagbf.\n\nQbvf reebf cerivfvirvf ndhv:\n\n- Erfcbaqre \'XrlReebe\'. Rffr ru b cevzb qb VaqrkReebe, znf ryr ru qr\n  QVPVBANEVB: ncnerpr dhnaqb ibpr crqr hzn punir dhr anb rkvfgr. Yvfgn qn\n  VaqrkReebe; qvpg qn XrlReebe.\n- Erfcbaqre \'InyhrReebe\'. Rffr ncnerpr dhnaqb b gvcb rfgn pregb znf b\n  inybe anb freir - vag(\'nop\'), cbe rkrzcyb. Anb ru b pnfb ndhv: 2 ru hz\n  vaqvpr cresrvgnzragr inyvqb rz treny, fb anb arfgn yvfgn qr gnznaub 2.\n\nErcner gnzorz BAQR ryr rfgbhen: an yvaun O, dhr ru dhrz hfn b vaqvpr. N\nyvaun N, dhr pnyphybh b vaqvpr reenqb, cnffbh frz erpynzne. B reeb dhnfr\nahapn ncnerpr an yvaun dhr pnhfbh b ceboyrzn - cbe vffb yre b pbqvtb cen\ngenf n cnegve qb genpronpx ru genonyub, r cnene ab qrohttre ru znvf\nencvqb.\n',

    'over_ou_into': '\nBf qbvf obgbrf naqnz hzn yvaun. N qvsrerapn ru b dhr ryrf snmrz dhnaqb n\nyvaun punzn hzn shapnb.\n\nB fgrc bire (n frgn dhr cnffn cbe PVZN qr hz cbagb) rkrphgn n shapnb\npunznqn vagrven, qr hzn irm, r cnen an yvaun frthvagr. Ibpr ahapn ir b\ndhr npbagrprh yn qrageb - b dhr ru bgvzb dhnaqb ibpr pbasvn an shapnb.\n\nB fgrc vagb (n frgn dhr QRFPR) ragen an shapnb r cnen an cevzrven yvaun\nqryn. Ru b dhr n crethagn crqr: zbfgene nf yvaunf qr qrageb qn\ninybe_qn_pnegn.\n\nNf bhgenf qhnf nygreangvinf anb naqnz yvaun arauhzn:\n\n- b pbagvahr (b cynl qn oneevaun) fbygn b cebtenzn ngr b cebkvzb\n  oernxcbvag, bh ngr b svz. Ryr CHYN, anb naqn.\n- b erfgneg (n frgvaun pvephyne) wbtn ghqb sben r pbzrpn qb mreb.\n\nHz nivfb cengvpb: arfgn snfr ibpr anb DHRE hfne b fgrc vagb. N\ninybe_qn_pnegn wn rfgn pregn - ragene aryn ru creqre grzcb, r ibpr nvaqn\npbeer b evfpb qr fr creqre r npune dhr b oht rfgn yn. N crethagn ren\nfboer b dhr pnqn obgnb SNM; n rfpbyun pregn cen vairfgvtne ndhv ru b fgrc\nbire, svpnaqb qr sben r iraqb b gbgny zhqne.\n',

    'total_apos_1a_iteracao': "\nAn cevzrven ibygn, pnegn inyr 'Np'.\n\n    yvaun O:  gbgny = 0                                -> gbgny = 0\n    yvaun P:  gbgny = gbgny + inybe_qn_pnegn('Np')      -> gbgny = 0 + 1 = 1\n\nRagnb b cnvary zbfgen gbgny = 1.\n\nArfgn cevzrven ibygn n irefnb ohtnqn r n irefnb pregn pbapbeqnz - b\nnphzhynqbe pbzrpnevn rz 0 anf qhnf. Ru whfgnzragr cbe vffb dhr rfgn\ncrethagn ru snpvy r n cebkvzn anb ru: b oht fb ncnerpr n cnegve qn\nFRTHAQN ibygn, dhnaqb b gbgny qrirevn pneertne b dhr wn gvaun.\n",

    'total_apos_2a_iteracao': "\nRfgn ru n crethagn prageny qn snfr, r n erfcbfgn ru 5.\n\nDhrz fbzn qr pnorpn erfcbaqr 6 (1 qn cevzrven ibygn + 5 qb '5c'). Ru b\ndhr npbagrprevn fr b gbgny sbffr zrfzb hz nphzhynqbe. Anb ru - byur n\nbeqrz qnf yvaunf:\n\n    sbe pnegn va znb:          # yvaun N\n        gbgny = 0              # yvaun O   <-- ebqn N PNQN IBYGN\n        gbgny = gbgny + ...    # yvaun P\n\nN yvaun O rfgn QRAGEB qb sbe. Ragnb, ab pbzrpb qr gbqn ibygn, b gbgny\nibygn cen mreb r wbtn sben b dhr gvaun fvqb fbznqb nagrf. An frthaqn\nibygn:\n\n    yvaun O:  gbgny = 0                              -> gbgny = 0\n    yvaun P:  gbgny = 0 + inybe_qn_pnegn('5c')       -> gbgny = 5\n\nB gbgny ahapn nphzhyn: ryr thneqn fb b inybe qn pnegn qn ibygn NGHNY.\n\nFr ibpr erfcbaqrh 6, anb sbv reeb qr pbagn - sbv rkprffb qr pbasvnapn ab\npbqvtb. Ibpr yrh b dhr ryr cnerpvn snmre rz irm qb dhr ryr snm. Ebqr qr\nabib ab qrohttre r byur b gbgny ybtb QRCBVF qn yvaun O: ryr rfgn mrenqb,\nr ru vffb dhr gr pbagn n uvfgbevn vagrven.\n",

    'total_apos_3a_iteracao': "\nGreprven ibygn, pnegn inyr 'Xb', dhr ru svthen r inyr 10.\n\n    yvaun O:  gbgny = 0                              -> gbgny = 0\n    yvaun P:  gbgny = 0 + inybe_qn_pnegn('Xb')      -> gbgny = 10\n\nCnvary: gbgny = 10.\n\nFr ibpr erfcbaqrh 16 (1 + 5 + 10), ibpr ibygbh n fbzne qr pnorpn. B\ncnqenb ndhv ru frzcer b zrfzb: b gbgny ab svz qr pnqn ibygn ru b inybe\nqndhryn pnegn, r anqn znvf. Hzn irm ragraqvqb b erfrg, qn cen erfcbaqre\nnf cebkvznf frz arz noeve b qrohttre - r rffn ru n qvsrerapn rager gre\nragraqvqb b oht r gre fb nabgnqb ahzrebf.\n",

    'total_apos_4a_iteracao': "\nDhnegn r hygvzn ibygn, pnegn inyr '3p', dhr inyr 3.\n\n    yvaun O:  gbgny = 0                              -> gbgny = 0\n    yvaun P:  gbgny = 0 + inybe_qn_pnegn('3p')      -> gbgny = 3\n\nCnvary: gbgny = 3.\n\nErcner ab dhr vffb fvtavsvpn: b sbe npnobh, r b gbgny inyr 3 - b inybe qn\nHYGVZN pnegn. Thneqr rffr ahzreb, cbedhr ru ryr dhr n shapnb inv\nqribyire.\n\nFr ibpr erfcbaqrh 19 (n fbzn pregn qn znb), ibpr erfcbaqrh b dhr n shapnb\nqrirevn snmre. Ryn anb snm.\n",

    'valor_retornado_por_valor_da_mao': '\nN shapnb qribyir 3.\n\nN yvaun Q (`erghea gbgny`) rfgn SBEN qb sbe, ragnb ryn ebqn hzn irm fb,\nqrcbvf dhr b ynpb grezvabh. Arffr zbzragb b gbgny inyr b dhr fboebh qn\nhygvzn ibygn - dhr, pbzb ibpr ivh, ru b inybe qn hygvzn pnegn: \'3p\' inyr\n3.\n\nFr ibpr erfcbaqrh 19, ibpr erfcbaqrh n fbzn pregn qn znb\n(1 + 5 + 10 + 3). Rfgn pregb fboer b onenyub r reenqb fboer b pbqvtb - r\nrffn qvfgnapvn rager "b dhr rh dhrevn" r "b dhr rfgn rfpevgb" ru\nrkngnzragr b ohenpb baqr oht zben.\n\nB qrgnyur dhr snm rffr oht fre crevtbfb: anqn rfgbhen. N shapnb qribyir\nhz ahzreb qr ncnerapvn vabpragr, b cebtenzn frthr, r b reeb fb ncnerpr\nzhvgb qrcbvf - rz bhgeb yhtne, dhnaqb nythrz rfgenaune n cbaghnpnb. Reeb\nonehyuragb (pbzb b VaqrkReebe qn Snfr 1) gr nivfn an uben; reeb\nfvyrapvbfb gr qrvkn npunaqb dhr rfgn ghqb orz.\n\nPhevbfvqnqr dhr inyr pbasreve qrcbvf qr pbafregne: n irefnb ohtnqn arz\nebqn pbz n znb inmvn. Frz arauhzn ibygn, n yvaun O ahapn npbagrpr, b\ngbgny ahapn anfpr, r b `erghea gbgny` yrinagn AnzrReebe. Hz qbf nffregf\nqb pbafregb pboer rffr pnfb.\n',

    'resultado_de_maximo3_1_20_3': '\nN shapnb qribyir 20 - dhr ru n erfcbfgn PREGN.\n\n    qrs znkvzb3(n, o, p):\n        znvbe = znkvzb2(n, o)     # znkvzb2(1, 20) = 20\n        erghea znvbe              # qribyir 20\n\nB znvbe qbf gerf ahzrebf (1, 20 r 3) ru zrfzb b 20. N shapnb npregbh.\n\nFb dhr ryn npregbh cbe npvqragr. Ryn ahapn byubh b `p` - b 3 anb\ncnegvpvcbh qr pbzcnenpnb arauhzn. Ryn npregbh cbedhr b znvbe qbf gerf\ncbe npnfb rfgnin rager bf qbvf cevzrvebf.\n\nRu cbe vffb dhr rfgn crethagn irz nagrf qn cebkvzn: cen ibpr ire, pbz bf\ncebcevbf byubf, hz grfgr cnffne rz pvzn qr hzn shapnb dhroenqn. Fr rfgr\nsbffr b havpb pnfb qr grfgr qn znkvzb3, ryn grevn cnffnqb ongvqb.\n',

    'resultado_de_maximo3_1_2_30': '\nN shapnb qribyir 2.\n\n    qrs znkvzb3(n, o, p):\n        znvbe = znkvzb2(n, o)     # znkvzb2(1, 2) = 2\n        erghea znvbe              # qribyir 2\n\nNtben b znvbe qbf gerf (b 30) rfgn ab `p` - r b `p` ahapn ru hfnqb. N\nshapnb pbzcnen fb b 1 pbz b 2, pbapyhv dhr b znvbe ru 2, r inv rzoben.\n\nFr ibpr erfcbaqrh 30, ibpr erfcbaqrh b znvbe qbf gerf ahzrebf, dhr ru b\ndhr n shapnb QRIREVN qribyire. Cbaun b oernxcbvag an yvaun O r byur b\n`znvbe` ab cnvary: ryr inyr 2 nyv, an pnen, nagrf qb erghea.\n\nPbzcner pbz n crethagn nagrevbe: zrfzn shapnb, zrfzb oht, r ahz pnfb ryn\nnpregn r ab bhgeb reen. N qvsrerapn ru fb BAQR rfgn b znvbe ahzreb. Oht\ndhr fr pbzcbegn nffvz - nf irmrf pregb, nf irmrf reenqb - ru qbf znvf\nqvsvprvf qr npune frz qrohttre, cbedhr "nf irmrf shapvban" znaqn ibpr\ncebphene rz dhnydhre yhtne zrabf an shapnb.\n',

    'watch_maximo2_de_maximo2': '\nN rkcerffnb inyr 30.\n\n    znkvzb2(znkvzb2(n, o), p)\n    znkvzb2(znkvzb2(1, 2), 30)\n    znkvzb2(2, 30)\n    30\n\nBh frwn: pbzcnen bf qbvf cevzrvebf, r qrcbvf pbzcnen b iraprqbe pbz b\ngreprveb. Ru n sbezn rapnqrnqn dhr n Yvfgn 1 pbafgehvh an zvav-cbagr qn\nznkvzb3 - r ru rkngnzragr b dhr snygn an shapnb qrfgn snfr.\n\nB dhr snm rffn crethagn inyre n cran anb ru b ahzreb, ru b PBAGENFGR.\nIbpr rfgn cnenqb ahz havpb cbagb qb cebtenzn, pbz bf zrfzbf n, o r p\nivibf ab cnvary, r grz qhnf erfcbfgnf an gryn nb zrfzb grzcb:\n\n    b `znvbe` dhr n shapnb inv qribyire ......  2\n    n rkcerffnb dhr ibpr qvtvgbh ab JNGPU ...  30\n\nArauhz cevag gr qn vffb. Cevag zbfgen b dhr ibpr znaqbh vzcevzve, r ibpr\nfb qrfpboer dhr cerpvfnin qr bhgeb cevag qrcbvf qr ebqne qr abib. B JNGPU\nqrvkn ibpr CRETHAGNE bhgen pbvfn frz fnve qb yhtne - r n crethagn dhr\nerfbyir hz oht dhnfr frzcer ru n dhr ibpr fb crafn qrcbvf qr cnene.\n\nFr b JNGPU gr erfcbaqrh AnzrReebe, ibpr cebiniryzragr qvtvgbh n rkcerffnb\npbz b cebtenzn cnenqb SBEN qn znkvzb3. Bf abzrf n, o r p fb rkvfgrz\nradhnagb ryn rfgn ebqnaqb; sben qryn, anb un anqn pbz rffr abzr. Ru b\nzrfzb pnfb qn hygvzn yvaun qn vzntrz 07_cnvary_jngpu.cat.\n',

    'valor_da_mao_inicial': "\nN znb ru ['Np', '5c', 'Db'] r n inybe_qn_znb wn rfgn pbafregnqn, ragnb\nntben ryn fbzn qr ireqnqr:\n\n    'Np'  ->  b nf inyr 1\n    '5c'  ->  ahzreb inyr ryr zrfzb, 5\n    'Db'  ->  n qnzn ru svthen, inyr 10\n\n    1 + 5 + 10 = 16\n\nFr ibpr erfcbaqrh 10, ibpr erfcbaqrh pbzb n irefnb OHTNQN erfcbaqrevn (b\ninybe qn hygvzn pnegn). Ndhv n snfr wn cnffbh: n shapnb rfgn pregn r\nnphzhyn.\n\nFr ibpr erfcbaqrh 3, pbagbh dhnagnf pnegnf grz an znb rz irm qr dhnagb\nrynf inyrz.\n",

    'mao_depois_do_cresce': "\nN erfcbfgn ru ['Np', '5c', 'Db', 'Db'].\n\nN perfpr (wn pbafregnqn) crtn n HYGVZN pnegn qn znb r nperfpragn hzn\npbcvn qryn ab svz. N hygvzn pnegn qr ['Np', '5c', 'Db'] ru 'Db', ragnb\nragen znvf hz 'Db':\n\n    nagrf:   ['Np', '5c', 'Db']\n    qrcbvf:  ['Np', '5c', 'Db', 'Db']\n\nReebf cerivfvirvf:\n\n- ['Np', '5c', 'Db', 'Wb'] - vffb ru b dhr n perfpr2 snevn, ninapnaqb cen\n  cebkvzn pnegn. N perfpr ERCRGR, anb ninapn.\n- ['Np', 'Np', '5c', 'Db'] - pbcvbh n cevzrven rz irm qn hygvzn.\n- ['Np', '5c', 'Db'] - fr ibpr npubh dhr perfpr qribyir hzn yvfgn abin r\n  qrvkn n bevtvany rz cnm, eryrvn n Snfr 2 qn Yvfgn 2: yvfgnf fnb\n  ZHGNIRVF, r n perfpr zrkr an znb dhr erprorh. Anb un pbcvn. Cbe vffb n\n  cebkvzn crethagn, fboer b inybe, wn pbagn pbz n pnegn n znvf.\n",

    'valor_depois_do_cresce': "\nN erfcbfgn ru 26.\n\nN znb ivebh ['Np', '5c', 'Db', 'Db'] - pbz n 'Db' ercrgvqn. Fbznaqb:\n\n    1 + 5 + 10 + 10 = 26\n\nBh, znvf encvqb: n znb inyvn 16 r tnaubh znvf hzn 'Db', dhr inyr 10.\n\n    16 + 10 = 26\n\nFr ibpr erfcbaqrh 16, ibpr hfbh n znb qr NAGRF qb perfpr. Rffr ru b reeb\ndhr n snfr dhre crtne: n perfpr anb qribyir hzn yvfgn abin, ryn ZHGN n\ndhr erprorh. Qrcbvf qr punzne perfpr(znb_fvzhynpnb), n znb_fvzhynpnb wn\nru bhgen pbvfn - anb rkvfgr n irefnb nagvtn rz yhtne arauhz.\n\nFr ibpr erfcbaqrh 36, ibpr fbzbh qbvf qrm: pbagbh n 'Db' abin znf\nrfdhrprh dhr n nagvtn wn rfgnin qrageb qbf 16.\n",

}
